import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Inventory Management App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>        
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png" />
        <link rel="icon" type="image/png" href="/assets/img/favicon.png" />              
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />        
        <script src="https://kit.fontawesome.com/42d5adcbca.js" crossOrigin="anonymous" defer></script>        
        <link href="/assets/css/nucleo-icons.css" rel="stylesheet" />
        <link href="/assets/css/nucleo-svg.css" rel="stylesheet" />        
        <script src="https://unpkg.com/@popperjs/core@2" defer></script>        
        <link href="/assets/css/argon-dashboard-tailwind.css?v=1.0.1" rel="stylesheet" />
      </head>

      <body className={`${inter.className} m-0 font-sans text-base antialiased font-normal dark:bg-slate-900 leading-default bg-gray-50 text-slate-500`}>
        <div className="absolute w-full bg-blue-500 dark:hidden min-h-75"></div>        
        {children}        
        <div fixed-plugin="true">
          <a fixed-plugin-button="true" className="fixed px-4 py-2 text-xl bg-white shadow-lg cursor-pointer bottom-8 right-8 z-990 rounded-circle text-slate-700">
            <i className="py-2 pointer-events-none fa fa-cog"> </i>
          </a>        
          <div fixed-plugin-card="true" className="z-sticky backdrop-blur-2xl backdrop-saturate-200 dark:bg-slate-850/80 shadow-3xl w-90 ease -right-90 fixed top-0 left-auto flex h-full min-w-0 flex-col break-words rounded-none border-0 bg-white/80 bg-clip-border px-2.5 duration-200">
            <div className="px-6 pt-4 pb-0 mb-0 border-b-0 rounded-t-2xl">
              <div className="float-left">
                <h5 className="mt-4 mb-0 dark:text-white">Argon Configurator</h5>
                <p className="dark:text-white dark:opacity-80">See our dashboard options.</p>
              </div>
              <div className="float-right mt-6">
                <button fixed-plugin-close-button="true" className="inline-block p-0 mb-4 text-sm font-bold leading-normal text-center uppercase align-middle transition-all ease-in bg-transparent border-0 rounded-lg shadow-none cursor-pointer hover:-translate-y-px tracking-tight-rem bg-150 bg-x-25 active:opacity-85 dark:text-white text-slate-700">
                  <i className="fa fa-close"></i>
                </button>
              </div>            
            </div>
            <hr className="h-px mx-0 my-1 bg-transparent bg-gradient-to-r from-transparent via-black/40 to-transparent dark:bg-gradient-to-r dark:from-transparent dark:via-white dark:to-transparent" />
            <div className="flex-auto p-6 pt-0 overflow-auto sm:pt-4">            
              <div>
                <h6 className="mb-0 dark:text-white">Sidebar Colors</h6>
              </div>
              <a href="javascript:void(0)">
                <div className="my-2 text-left" sidenav-colors="true">
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-blue-500 to-violet-500 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-slate-700 text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" active-color data-color="blue"></span>
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-zinc-800 to-zinc-700 dark:bg-gradient-to-tl dark:from-slate-750 dark:to-gray-850 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-white text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" data-color="gray"></span>
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-blue-700 to-cyan-500 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-white text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" data-color="cyan"></span>
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-emerald-500 to-teal-400 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-white text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" data-color="emerald"></span>
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-orange-500 to-yellow-500 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-white text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" data-color="orange"></span>
                  <span className="py-2.2 text-xs rounded-circle h-5.6 mr-1.25 w-5.6 ease-in-out bg-gradient-to-tl from-red-600 to-orange-600 relative inline-block cursor-pointer whitespace-nowrap border border-solid border-white text-center align-baseline font-bold uppercase leading-none text-white transition-all duration-200 hover:border-slate-700" data-color="red"></span>
                </div>
              </a>            
              <div className="mt-4">
                <h6 className="mb-0 dark:text-white">Sidenav Type</h6>
                <p className="text-sm leading-normal dark:text-white dark:opacity-80">Choose between 2 different sidenav types.</p>
              </div>
              <div className="flex">
                <button transparent-style-btn="true" className="inline-block w-full px-4 py-2.5 mb-2 font-bold leading-normal text-center text-white capitalize align-middle transition-all bg-blue-500 border border-transparent border-solid rounded-lg cursor-pointer text-sm xl-max:cursor-not-allowed xl-max:opacity-65 xl-max:pointer-events-none xl-max:bg-gradient-to-tl xl-max:from-blue-500 xl-max:to-violet-500 xl-max:text-white xl-max:border-0 hover:-translate-y-px dark:cursor-not-allowed dark:opacity-65 dark:pointer-events-none dark:bg-gradient-to-tl dark:from-blue-500 dark:to-violet-500 dark:text-white dark:border-0 hover:shadow-xs active:opacity-85 ease-in tracking-tight-rem shadow-md bg-150 bg-x-25 bg-gradient-to-tl from-blue-500 to-violet-500 hover:border-blue-500" data-classname="bg-transparent" active-style="true">White</button>
                <button white-style-btn="true" className="inline-block w-full px-4 py-2.5 mb-2 ml-2 font-bold leading-normal text-center text-blue-500 capitalize align-middle transition-all bg-transparent border border-blue-500 border-solid rounded-lg cursor-pointer text-sm xl-max:cursor-not-allowed xl-max:opacity-65 xl-max:pointer-events-none xl-max:bg-gradient-to-tl xl-max:from-blue-500 xl-max:to-violet-500 xl-max:text-white xl-max:border-0 hover:-translate-y-px dark:cursor-not-allowed dark:opacity-65 dark:pointer-events-none dark:bg-gradient-to-tl dark:from-blue-500 dark:to-violet-500 dark:text-white dark:border-0 hover:shadow-xs active:opacity-85 ease-in tracking-tight-rem shadow-md bg-150 bg-x-25 bg-none hover:border-blue-500" data-classname="bg-white">Dark</button>
              </div>
              <p className="block mt-2 leading-normal text-sm dark:text-white dark:opacity-80 xl-max:hidden">You can change the sidenav type just on desktop view.</p>
              <div className="flex my-4">
                <h6 className="mb-0 dark:text-white">Navbar Fixed</h6>
                <div className="min-h-6 mb-0.5 block pl-0 ml-auto">
                  <input id="navbarFixed" className="mt-0.54 rounded-10 duration-250 ease-in-out after:rounded-circle after:shadow-xs after:duration-250 after:ease-in-out checked:bg-blue-500/95 checked:after:-ml-1.25 checked:after:translate-x-5.25 checked:after:bg-white/95 float-left h-5 w-10 cursor-pointer appearance-none border border-solid border-slate-200 bg-slate-400/20 bg-none bg-left bg-no-repeat align-top transition-all leading-tight" type="checkbox" />
                </div>
              </div>            
              <hr className="h-px bg-transparent bg-gradient-to-r from-transparent via-black/40 to-transparent dark:bg-gradient-to-r dark:from-transparent dark:via-white dark:to-transparent" />
              <div className="mt-2 mb-12">
                <h6 className="mb-0 dark:text-white">Sidenav Mini</h6>
                <div className="min-h-6 mb-0.5 block pl-0 ml-auto">
                  <input id="navbtn" className="mt-0.54 rounded-10 duration-250 ease-in-out after:rounded-circle after:shadow-xs after:duration-250 after:ease-in-out checked:bg-blue-500/95 checked:after:-ml-1.25 checked:after:translate-x-5.25 checked:after:bg-white/95 float-left h-5 w-10 cursor-pointer appearance-none border border-solid border-slate-200 bg-slate-400/20 bg-none bg-left bg-no-repeat align-top transition-all leading-tight" type="checkbox" />
                </div>
              </div>
              <hr className="h-px bg-transparent bg-gradient-to-r from-transparent via-black/40 to-transparent dark:bg-gradient-to-r dark:from-transparent dark:via-white dark:to-transparent" />
              <div className="mt-2 mb-12">
                <h6 className="mb-0 dark:text-white">Navbar Fixed</h6>
                <div className="min-h-6 mb-0.5 block pl-0 ml-auto">
                  <input id="navbarFixed" className="mt-0.54 rounded-10 duration-250 ease-in-out after:rounded-circle after:shadow-xs after:duration-250 after:ease-in-out checked:bg-blue-500/95 checked:after:-ml-1.25 checked:after:translate-x-5.25 checked:after:bg-white/95 float-left h-5 w-10 cursor-pointer appearance-none border border-solid border-slate-200 bg-slate-400/20 bg-none bg-left bg-no-repeat align-top transition-all leading-tight" type="checkbox" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </body>
      <script src={"/assets/js/plugins/chartjs.min.js"} async></script>  
      <script src={"/assets/js/plugins/perfect-scrollbar.min.js"} async></script>
      <script src={"/assets/js/argon-dashboard-tailwind.js?v=1.0.1"} async></script>
    </html>
  )
}
